import re

DROPBOX_LOCAL_PATH = f"INSERT LOCAL PATH TO DROPBOX FOLDER HERE"
DROPBOX_BRANCH = "test"
MOMBOT_ROOT_DIR = f"{DROPBOX_LOCAL_PATH}/{DROPBOX_BRANCH}"

COMMAND_FILE_REGEX = re.compile(r"batch-(\d{6})_(\S+)\.json")

AVAILABLE_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/batches_available_for_medea'
IN_PROGRESS_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/data'
ARCHIVE_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/archive'
COMMANDS_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/pending'
FAILED_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/failed'
MOMBOT_STATUS_FILE_PATH = f'{MOMBOT_ROOT_DIR}/mombot/status.json'
BATCHES_FROM_TUFTS_FOLDER_PATH = f'{MOMBOT_ROOT_DIR}/mombot/new_batches_from_tufts'

MIN_CAMERA_DELAY_MS = 5000
INITIAL_VIDEO_DURATION_MS = 900000
POST_INTERVENTION_OBSERVATION_PERIOD_MS = 900000
INVERSE_TIMEOUT_MS = 300000
INTERVENTION_LENGTH_MS = 180000
